title: "[플랫폼] "
labels: 제목
body:
  - type: input
    id: link
    attributes:
      label: 문제 링크
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      value: |
        ### 문제 설명
  
        <br/>
  
        ---
  
        ### 아이디어
  
        <br/>
  
        ---
  
        ### 시간 복잡도
  
        <br/>
    validations:
      required: true
  - type: textarea
    id: java-code
    attributes:
      label: 구현
      render: java
    validations:
      required: true
