title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    attributes:
      label: 문제 설명
      value: |
        ## 제목
  
        문제: 
        
        <br/>
        
        ---
  
        ### 문제 설명
  
  
        <br/>
        
        ---
  
        ### 아이디어
  
  
        <br/>
        
        ---
  
        ### 시간 복잡도
  
  
        <br/>
        
        ---
  
        ### 구현
  
        ```java

        
        ```
