title: "[플랫폼] "
labels: 제목
body:
  - type: input
    id: link
    attributes:
      label: 문제 링크
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### 문제 설명
  
  
        <br/>
        
        ---
  
        ### 아이디어
  
  
        <br/>
        
        ---
  
        ### 시간 복잡도
  
  
        <br/>
        
        ---
  
        ### 구현
  
        ```java

        
        ```
