title: "[플랫폼] "
labels: 제목
body:
  - type: input
    id: link
    attributes:
      label: 문제 링크
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 문제 설명
      render: markdown
    validations:
      required: true
  - type: textarea
    id: time
    attributes:
      label: 시간 복잡도
      render: markdown
    validations:
      required: true
  - type: textarea
    id: java-code
    attributes:
      label: 구현
      render: java
    validations:
      required: true
